[build]
publish = "hugo-theme-item/exampleSite/public"
command = "mkdir -p hugo-theme-item; mv ./* hugo-theme-item/; cd hugo-theme-item; yarn; yarn build"


[build.environment]
GO_VERSION = "1.22.0"
HUGO_VERSION = "0.130.0"